--鐢ㄦ埛琛�
CREATE TABLE "HR"."T_USER" 
   (	"USER_ID" NUMBER, 
	"USER_NAME" VARCHAR2(30), 
	"CREDITS" NUMBER(*,0), 
	"PASSWORD" VARCHAR2(50), 
	"LAST_VISIT" TIMESTAMP (6), 
	"LAST_IP" VARCHAR2(23), 
	"NICK_NAME" VARCHAR2(50), 
	"MOBILE_PHONE" VARCHAR2(50), 
	"REAL_NAME" VARCHAR2(50), 
	"ADDRESS" VARCHAR2(100), 
	"POST_CARD" VARCHAR2(30), 
	"USER_IMG" VARCHAR2(100), 
	"CONTINUOUS_LOGIN_TIMES" NUMBER, 
	 CONSTRAINT "T_USERID" PRIMARY KEY ("USER_ID")
  USING INDEX REVERSE PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "HR"."USER_ID_INDEX" ON "HR"."T_USER" ("USER_ID") REVERSE 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "HR"."T_USER" ADD CONSTRAINT "T_USERID" PRIMARY KEY ("USER_ID")
  USING INDEX REVERSE PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--鏃ュ織琛�
CREATE TABLE "HR"."T_LOGIN_LOG" 
   (	"LOGIN_LOG_ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0), 
	"IP" VARCHAR2(23), 
	"LOGIN_DATETIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  --鍦板潃琛�
CREATE TABLE "HR"."T_ADDRESS" 
   (	"USER_ID" NUMBER(*,0), 
	"ADDRESS" VARCHAR2(200)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--鐢ㄦ埛琛↖D SEQUENCE
  CREATE SEQUENCE  "HR"."USERINFO_SEQUENCE"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1671336 NOCACHE  NOORDER  NOCYCLE ;
--鍟嗗搧绫诲埆琛�
  CREATE TABLE "HR"."ITEM_CAT" 
   (	"CID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(50), 
	"PARENT_CID" NUMBER, 
	"IS_PARENT" NUMBER, 
	"STATUS" NUMBER, 
	"SORT_ORDER" NUMBER, 
	"MODIFIED_TIME" DATE, 
	 CONSTRAINT "ICID" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "HR"."ICID" ON "HR"."ITEM_CAT" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "HR"."ITEM_CAT" ADD CONSTRAINT "ICID" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."ITEM_CAT" MODIFY ("CID" NOT NULL ENABLE);

  -- Create sequence 
create sequence ITEMCAT_SEQ
minvalue 1
maxvalue 9999999999
start with 1
increment by 1
cache 20;

--itemCat  初始化数据
insert into item_cat (CID, NAME, PARENT_CID, IS_PARENT, STATUS, SORT_ORDER, MODIFIED_TIME)
values (0, '产品类别', 999, 1, 1, 1, to_date('03-01-2014 23:11:36', 'dd-mm-yyyy hh24:mi:ss'));