--用户表
CREATE TABLE "HR"."T_USER" 
   (	"USER_ID" VARCHAR2(50), 
	"USER_NAME" VARCHAR2(30), 
	"CREDITS" NUMBER(*,0), 
	"PASSWORD" VARCHAR2(50), 
	"LAST_VISIT" TIMESTAMP (6), 
	"LAST_IP" VARCHAR2(23), 
	"NICK_NAME" VARCHAR2(50), 
	"MOBILE_PHONE" VARCHAR2(50), 
	"REAL_NAME" VARCHAR2(50), 
	"ADDRESS" VARCHAR2(100), 
	"POST_CARD" VARCHAR2(30), 
	"USER_IMG" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "HR"."USER_ID_INDEX" ON "HR"."T_USER" ("USER_ID") REVERSE 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--日志表
CREATE TABLE "HR"."T_LOGIN_LOG" 
   (	"LOGIN_LOG_ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0), 
	"IP" VARCHAR2(23), 
	"LOGIN_DATETIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  --地址表
CREATE TABLE "HR"."T_ADDRESS" 
   (	"USER_ID" NUMBER(*,0), 
	"ADDRESS" VARCHAR2(200)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--用户表ID SEQUENCE
  CREATE SEQUENCE  "HR"."USERINFO_SEQUENCE"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1671336 NOCACHE  NOORDER  NOCYCLE ;